### ISSUE TITLE
Weird number stored in ec_slave[1].state after trying to change the state to SAFE_OP 

### ISSUE THREAD

**Issue by mohse-n** [OpenEtherCATsociety/SOEM#198]
Hi. When I put my slave (a [Mecapion L7N](http://www.lsmecapion.com/eng/contents/sub01/sub01_02.php) servo drive) in PRE_OP mode and after I try to set its state to SAFE_OP, for some reason the state changes to 18, instead of 0x04 (which according to `ethercattype.h`, stands for SAFE_OP).
Consider the following snippet:
```
printf("%d",ec_slave[1].state);

ec_slave[1].state=EC_STATE_SAFE_OP;
ec_writestate(1);
if (ec_statecheck(1, EC_STATE_SAFE_OP, EC_TIMEOUTSTATE*4) == EC_STATE_SAFE_OP)
      printf("Slave 1 reached SAFE_OP state\n");

printf("%d",ec_slave[1].state);
```
The output is:
```
2
18
```
Clearly, 2 corresponds to PRE_OP state, but I have no idea what state is 18 associated with?

**Comment by ArthurKetels** [comment]
It is easier to print the EtherCAT state as hex. Then the above transition would be 0x02 to 0x12. This means PRE_OP to PRE_OP + ERROR. Clearly something is wrong with the configuration. And the slave refuses to go to SAFE_OP. By reading the error state of the slave you could see what went wrong. Otherwise post a (zipped) wireshark capture from the slave initialization. Then we could analyze more precise what went wrong.

As a remark, servo drives are sometimes more critical on set-up requirements. The manual of the drive should give you more information.

**Comment by ArthurKetels** [comment]
Thanks for the code and trace. It is completely explainable why the slave will complain going to SAFE_OP. You do the ec_config_init() but forget to also map the slave PDOs. Look at simpletest.c on how to do that.

SOEM must first read out the rxpdo and txpdo mapping (either SII, CoE or SoE), then configure the SM and FMMU's. Only then the state change to SAFE_OP can be requested. 

An extra thing to note is that for most servo drives there must be continuous PDO transfer during SAFE_OP and OP states, otherwise you get synchronisation errors.

**Comment by mohse-n** [comment]
Thanks for your answer and helpful note about servo drives. 
By "reading rxpdo and txpdo mapping", do you have a specific function in mind? Can you point out which lines of `simple_test.c` are related to that?
I took a look at `simple_test.c` and the two relevant differences compared to my code were the addition of `ec_config_map(&IOmap)` and `ec_configdc()` after `ec_config_init(FALSE)`. Alas, adding these lines didn't fix the error. This didn't surprise me, since running `simple_test.c` would also result in status 0x12.

**Comment by ArthurKetels** [comment]
OK, then please provide the wireshark trace of simple_test, and if possible the text output of slaveinfo with -map. This will give me some clues where the problem might reside.

The ec_config_map() will do the heavy lifting in figuring out the default slave PDO mapping and actually programming the SM en FMMU of the slave. ec_configdc() is related to distributing the same clock to all slaves. This will only affect slave to slave sync (and master). Activating this will not have any influence on the PDO mapping.

**Comment by mohse-n** [comment]
1- [Wireshark capture of simple_test](https://drive.google.com/file/d/1eRc31EKUPQA8O3BLFdorhy7OLhgaotVb/view?usp=sharing)
2- Output of slaveinfo with -map
```
SOEM (Simple Open EtherCAT Master)
Slaveinfo
Starting slaveinfo
ec_init on eth0 succeeded.
1 slaves found and configured.
Calculated workcounter 3
Not all slaves reached safe operational state.
Slave 1 State=12 StatusCode=  1e : Invalid input configuration

Slave:1
 Name:L7N
 Output size: 48bits
 Input size: 48bits
 State: 18
 Delay: 0[ns]
 Has DC: 1
 DCParentport:0
 Activeports:1.0.0.0
 Configured address: 1001
 Man: 00007595 ID: 00000000 Rev: 00000002
 SM0 A:1000 L: 128 F:00010026 Type:1
 SM1 A:1400 L: 128 F:00010022 Type:2
 SM2 A:1800 L:   6 F:00000024 Type:3
 SM3 A:1c00 L:   6 F:00000020 Type:4
 FMMU0 Ls:00000000 Ll:   6 Lsb:0 Leb:7 Ps:1800 Psb:0 Ty:02 Act:01
 FMMU1 Ls:00000006 Ll:   6 Lsb:0 Leb:7 Ps:1c00 Psb:0 Ty:01 Act:01
 FMMUfunc 0:1 1:2 2:0 3:0
 MBX length wr: 128 rd: 128 MBX protocols : 04
 CoE details: 0f FoE details: 00 EoE details: 00 SoE details: 00
 Ebus current: 0[mA]
 only LRD/LWR:1
PDO mapping according to CoE :
  SM2 outputs
     addr b   index: sub bitl data_type    name
  [0x0000.0] 0x6040:0x00 0x10 UNSIGNED16   Controlword
  [0x0002.0] 0x607A:0x00 0x20 INTEGER32    Target Position
  SM3 inputs
     addr b   index: sub bitl data_type    name
  [0x0006.0] 0x6041:0x00 0x10 UNSIGNED16   Statusword
  [0x0008.0] 0x6064:0x00 0x20 INTEGER32    Position Actual Value
End slaveinfo, close socket
End program

```

**Comment by ArthurKetels** [comment]
Thanks, the issue is in the SM2 and SM3 configuration. 

The slave states that SM2 and SM3 enabled=0. And this is what SOEM executes. When requesting safe-op the slave then complains the SM is not enabled and throws 0x1e in status code.

This is a firmware issue in the slave and has nothing to do with SOEM. But there is a work around. We can use the PO2SOconfig hook to reprogram the flags of this slave.
The hook function must at least set below SMflags.
`context->slavelist[slave].SM[2].SMflags |=EC_SMENABLEMASK);
context->slavelist[slave].SM[3].SMflags |=EC_SMENABLEMASK);`
And the hook must be defined before ec_config_map.

**Comment by ArthurKetels** [comment]
1. Wireshark tells you exactly what each bit in the SM flags are. And of course there is the official ETG documentation. 0x00010000 is the enable mask. Then there are 1-buffer and 3-buffer modes and read or write access. SM2 and SM3 are in your case used for PDO data and work in 3-buffer mode. The mailboxes of SM0 and SM1 work in 1-buffer mode.
2. Yes you are correct. Only the enable bit is missing in the Mecapion data.
3. Yes, an implementation bug in the Mecapion. I downloaded the XML file and it shows the same mistake. It is only by luck that for example TwinCAT simply sets the enable bit no matter what the slave tells to do. I try to have SOEM behave as closely as possible to the standard and what the slaves are telling SOEM to do. It is easy to change SOEM to always enable active SM's but that could break in the future when new functions may come available. It is best to ask the manufacturer to address the issue and give you a firmware update. In the mean time you could use a work around.

**Comment by mohse-n** [comment]
Thanks for your help. I really appreciate your detailed answers. Enabling SM2 and SM3 fixed the issue. So I can now go from PRE_OP to SAFE_OP and also SAFE_OP to OPERATIONAL without an issue. The fixed code look like this:
```
char IOmap[4096];

void initialize (char *ifname)
{
	if (ec_init(ifname))
	{
		printf("ec_init on %s succeeded. \n",ifname);

		if (ec_config_init(FALSE) > 0)
		{		
			printf("%d slaves found and PRE_OP state requested\n", ec_slavecount);
				if (ec_statecheck(0, EC_STATE_PRE_OP, EC_TIMEOUTSTATE) == EC_STATE_PRE_OP)
					printf("All slaves reached PRE_OP state\n");

                       ec_slave[1].SM[2].SMflags |= 0x00010000;
                       ec_slave[1].SM[3].SMflags |= 0x00010000;

                       ec_config_map(&IOmap);
		}
	}
}

int main(int argc, char *argv[])
{
initialize(argv[1]);
printf("%d",ec_slave[1].state);
ec_slave[1].state=EC_STATE_SAFE_OP;
ec_writestate(1);
if (ec_statecheck(1, EC_STATE_SAFE_OP, EC_TIMEOUTSTATE*4) == EC_STATE_SAFE_OP)
	printf("All slaves reached SAFE_OP state\n");
printf("Slave %d State=0x%2.2x StatusCode=0x%4.4x : %s\n", 1, ec_slave[1].state, ec_slave[1].ALstatuscode, ec_ALstatuscode2string(ec_slave[1].ALstatuscode)); 
 }    
```
I could also just use `EC_SMENABLEMASK `(which is defined in ethercatmain.h) instead of `0x00010000`.
